ALTER TABLE events DROP COLUMN IF EXISTS client_id;
DROP TABLE IF EXISTS clients;
ALTER TABLE events DROP COLUMN IF EXISTS budget;
ALTER TABLE events DROP COLUMN IF EXISTS vendor_currency;
ALTER TABLE events DROP COLUMN IF EXISTS location;
ALTER TABLE events DROP COLUMN IF EXISTS date;
ALTER TABLE events DROP COLUMN IF EXISTS event_type;
